root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - prettier
extends:
  - google
  - plugin:prettier/recommended
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
rules:
  prettier/prettier: error
  valid-jsdoc: warn
  require-jsdoc: warn
  new-cap: warn
