apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
data:
  {{- $files := .Files }}
  {{- range tuple "config.yaml" }}
  {{ . }}: |-
    {{- $files.Get . | nindent 4 -}}
  {{- end }}
