#!/bin/bash
export DOCKER_REGISTRY=${DOCKER_REGISTRY:-""}

for platform in linux/arm/v7, linux/arm64/v8, linux/amd64; do

DOCKER_BUILDKIT=1 docker build \
--platform $platform \
--progress=plain \
-t ${DOCKER_REGISTRY}/st-api-server:latest-$platform .

done
