#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Removing installed node modules..."
rm -rf node_modules/

echo "==> Installing node dependencies..."
npm install

echo "==> App is now ready to go!"
