name: GitHub Actions Build-Push Image
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Build Environment
        run: npm ci

      - name: Build Dist
        run: npm run build

      - name: Install cosign
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: sigstore/cosign-installer@v2.2.1

      - name: Set up QEMU
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: arm,arm64

      - name: Setup Docker Buildx
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log into Registry ${{ env.REGISTRY }}
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/metadata-action@v3.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Image
        if: ${{ github.ref == 'refs/heads/main' }}
        id: build-and-push
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Sign the published Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          COSIGN_EXPERIMENTAL: 1
        run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
